package sap_api_input_reader

type EC_MC struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	Document      struct {
		DocumentNo     string `json:"document_no"`
		DeliverTo      string `json:"deliver_to"`
		Quantity       string `json:"quantity"`
		PickedQuantity string `json:"picked_quantity"`
		Price          string `json:"price"`
		Batch          string `json:"batch"`
	} `json:"document"`
	ProductionOrder struct {
		DocumentNo           string `json:"document_no"`
		Status               string `json:"status"`
		DeliverTo            string `json:"deliver_to"`
		Quantity             string `json:"quantity"`
		CompletedQuantity    string `json:"completed_quantity"`
		PlannedStartDate     string `json:"planned_start_date"`
		PlannedValidatedDate string `json:"planned_validated_date"`
		ActualStartDate      string `json:"actual_start_date"`
		ActualValidatedDate  string `json:"actual_validated_date"`
		Batch                string `json:"batch"`
		Work                 struct {
			WorkNo                   string `json:"work_no"`
			Quantity                 string `json:"quantity"`
			CompletedQuantity        string `json:"completed_quantity"`
			ErroredQuantity          string `json:"errored_quantity"`
			Component                string `json:"component"`
			PlannedComponentQuantity string `json:"planned_component_quantity"`
			PlannedStartDate         string `json:"planned_start_date"`
			PlannedStartTime         string `json:"planned_start_time"`
			PlannedValidatedDate     string `json:"planned_validated_date"`
			PlannedValidatedTime     string `json:"planned_validated_time"`
			ActualStartDate          string `json:"actual_start_date"`
			ActualStartTime          string `json:"actual_start_time"`
			ActualValidatedDate      string `json:"actual_validated_date"`
			ActualValidatedTime      string `json:"actual_validated_time"`
		} `json:"work"`
	} `json:"production_order"`
	APISchema      string `json:"api_schema"`
	MaterialCode   string `json:"material_code"`
	Plant_Supplier string `json:"plant/supplier"`
	Stock          string `json:"stock"`
	DocumentType   string `json:"document_type"`
	DocumentNo     string `json:"document_no"`
	PlannedDate    string `json:"planned_date"`
	ValidatedDate  string `json:"validated_date"`
	Deleted        bool   `json:"deleted"`
}

type SDC struct {
	ConnectionKey     string `json:"connection_key"`
	Result            bool   `json:"result"`
	RedisKey          string `json:"redis_key"`
	Filepath          string `json:"filepath"`
	PartnerCollection struct {
		ObjectID                          string `json:"ObjectID"`
		PartnerID                         string `json:"PartnerID"`
		PartnerUUID                       string `json:"PartnerUUID"`
		LifeCycleStatusCode               string `json:"LifeCycleStatusCode"`
		LifeCycleStatusCodeText           string `json:"LifeCycleStatusCodeText"`
		Duns                              string `json:"DUNS"`
		LegalFormCode                     string `json:"LegalFormCode"`
		LegalFormCodeText                 string `json:"LegalFormCodeText"`
		PartnerABCClassificationCode      string `json:"PartnerABCClassificationCode"`
		PartnerABCClassificationCodeText  string `json:"PartnerABCClassificationCodeText"`
		IndustrialSectorCode              string `json:"IndustrialSectorCode"`
		IndustrialSectorCodeText          string `json:"IndustrialSectorCodeText"`
		ContactPermissionCode             string `json:"ContactPermissionCode"`
		ContactPermissionCodeText         string `json:"ContactPermissionCodeText"`
		BusinessPartnerFormattedName      string `json:"BusinessPartnerFormattedName"`
		Name                              string `json:"Name"`
		AdditionalName                    string `json:"AdditionalName"`
		AdditionalName2                   string `json:"AdditionalName2"`
		AdditionalName3                   string `json:"AdditionalName3"`
		FormattedPostalAddressDescription string `json:"FormattedPostalAddressDescription"`
		CountryCode                       string `json:"CountryCode"`
		CountryCodeText                   string `json:"CountryCodeText"`
		StateCode                         string `json:"StateCode"`
		StateCodeText                     string `json:"StateCodeText"`
		CareOfName                        string `json:"CareOfName"`
		AddressLine1                      string `json:"AddressLine1"`
		AddressLine2                      string `json:"AddressLine2"`
		HouseNumber                       string `json:"HouseNumber"`
		Street                            string `json:"Street"`
		AddressLine4                      string `json:"AddressLine4"`
		AddressLine5                      string `json:"AddressLine5"`
		District                          string `json:"District"`
		City                              string `json:"City"`
		DifferentCity                     string `json:"DifferentCity"`
		StreetPostalCode                  string `json:"StreetPostalCode"`
		County                            string `json:"County"`
		CompanyPostalCode                 string `json:"CompanyPostalCode"`
		POBox                             string `json:"POBox"`
		POBoxPostalCode                   string `json:"POBoxPostalCode"`
		POBoxDeviatingCountryCode         string `json:"POBoxDeviatingCountryCode"`
		POBoxDeviatingCountryCodeText     string `json:"POBoxDeviatingCountryCodeText"`
		POBoxDeviatingStateCode           string `json:"POBoxDeviatingStateCode"`
		POBoxDeviatingStateCodeText       string `json:"POBoxDeviatingStateCodeText"`
		POBoxDeviatingCity                string `json:"POBoxDeviatingCity"`
		TimeZoneCode                      string `json:"TimeZoneCode"`
		TimeZoneCodeText                  string `json:"TimeZoneCodeText"`
		Building                          string `json:"Building"`
		Floor                             string `json:"Floor"`
		Room                              string `json:"Room"`
		Phone                             string `json:"Phone"`
		Mobile                            string `json:"Mobile"`
		Fax                               string `json:"Fax"`
		Email                             string `json:"Email"`
		WebSite                           string `json:"WebSite"`
		LanguageCode                      string `json:"LanguageCode"`
		LanguageCodeText                  string `json:"LanguageCodeText"`
		BestReachedByCode                 string `json:"BestReachedByCode"`
		BestReachedByCodeText             string `json:"BestReachedByCodeText"`
		TotalPoints                       string `json:"TotalPoints"`
		PartnerLevel                      string `json:"PartnerLevel"`
		PartnerLevelText                  string `json:"PartnerLevelText"`
		NormalisedPhone                   string `json:"NormalisedPhone"`
		NormalisedMobile                  string `json:"NormalisedMobile"`
		CreatedOn                         string `json:"CreatedOn"`
		CreatedBy                         string `json:"CreatedBy"`
		CreatedByIdentityUUID             string `json:"CreatedByIdentityUUID"`
		ChangedOn                         string `json:"ChangedOn"`
		ChangedBy                         string `json:"ChangedBy"`
		ChangedByIdentityUUID             string `json:"ChangedByIdentityUUID"`
		EntityLastChangedOn               string `json:"EntityLastChangedOn"`
		ETag                              string `json:"ETag"`
	} `json:"PartnerCollection"`
	PartnerAddressCollection struct {
		ObjectID                          string `json:"ObjectID"`
		ParentObjectID                    string `json:"ParentObjectID"`
		PartnerID                         string `json:"PartnerID"`
		MainIndicator                     bool   `json:"MainIndicator"`
		ShipTo                            bool   `json:"ShipTo"`
		DefaultShipTo                     bool   `json:"DefaultShipTo"`
		BillTo                            bool   `json:"BillTo"`
		DefaultBillTo                     bool   `json:"DefaultBillTo"`
		FormattedPostalAddressDescription string `json:"FormattedPostalAddressDescription"`
		CountryCode                       string `json:"CountryCode"`
		CountryCodeText                   string `json:"CountryCodeText"`
		StateCode                         string `json:"StateCode"`
		StateCodeText                     string `json:"StateCodeText"`
		CareOfName                        string `json:"CareOfName"`
		AddressLine1                      string `json:"AddressLine1"`
		AddressLine2                      string `json:"AddressLine2"`
		HouseNumber                       string `json:"HouseNumber"`
		Street                            string `json:"Street"`
		AddressLine4                      string `json:"AddressLine4"`
		AddressLine5                      string `json:"AddressLine5"`
		District                          string `json:"District"`
		City                              string `json:"City"`
		DifferentCity                     string `json:"DifferentCity"`
		StreetPostalCode                  string `json:"StreetPostalCode"`
		County                            string `json:"County"`
		CompanyPostalCode                 string `json:"CompanyPostalCode"`
		POBoxIndicator                    bool   `json:"POBoxIndicator"`
		POBox                             string `json:"POBox"`
		POBoxPostalCode                   string `json:"POBoxPostalCode"`
		POBoxDeviatingCountryCode         string `json:"POBoxDeviatingCountryCode"`
		POBoxDeviatingCountryCodeText     string `json:"POBoxDeviatingCountryCodeText"`
		POBoxDeviatingStateCode           string `json:"POBoxDeviatingStateCode"`
		POBoxDeviatingStateCodeText       string `json:"POBoxDeviatingStateCodeText"`
		POBoxDeviatingCity                string `json:"POBoxDeviatingCity"`
		TimeZoneCode                      string `json:"TimeZoneCode"`
		TimeZoneCodeText                  string `json:"TimeZoneCodeText"`
		Building                          string `json:"Building"`
		Floor                             string `json:"Floor"`
		Room                              string `json:"Room"`
		Phone                             string `json:"Phone"`
		Mobile                            string `json:"Mobile"`
		Fax                               string `json:"Fax"`
		Email                             string `json:"Email"`
		WebSite                           string `json:"WebSite"`
		LanguageCode                      string `json:"LanguageCode"`
		LanguageCodeText                  string `json:"LanguageCodeText"`
		BestReachedByCode                 string `json:"BestReachedByCode"`
		BestReachedByCodeText             string `json:"BestReachedByCodeText"`
		NormalisedPhone                   string `json:"NormalisedPhone"`
		NormalisedMobile                  string `json:"NormalisedMobile"`
		ETag                              string `json:"ETag"`
	} `json:"PartnerAddressCollection"`
	PartnerProgramsCollection struct {
		ObjectID           string `json:"ObjectID"`
		ParentObjectID     string `json:"ParentObjectID"`
		PartnerProgram     string `json:"PartnerProgram"`
		PartnerProgramText string `json:"PartnerProgramText"`
		MembershipID       string `json:"MembershipID"`
		PartnerType        string `json:"PartnerType"`
		PartnerTypeText    string `json:"PartnerTypeText"`
		Status             string `json:"Status"`
		StatusText         string `json:"StatusText"`
		AgreementStartDate string `json:"AgreementStartDate"`
		AgreementEndDate   string `json:"AgreementEndDate"`
	} `json:"PartnerProgramsCollection"`
	PartnerProductDimensions struct {
		ObjectID            string `json:"ObjectID"`
		ParentObjectID      string `json:"ParentObjectID"`
		DimensionStatus     string `json:"DimensionStatus"`
		DimensionStatusText string `json:"DimensionStatusText"`
		ProductID           string `json:"ProductID"`
		StartDate           string `json:"StartDate"`
		EndDate             string `json:"EndDate"`
	} `json:"PartnerProductDimensions"`
	PartnerContactCollection struct {
		ObjectID            string `json:"ObjectID"`
		ParentObjectID      string `json:"ParentObjectID"`
		PartnerID           string `json:"PartnerID"`
		PartnerContactID    string `json:"PartnerContactID"`
		MainIndicator       bool   `json:"MainIndicator"`
		DepartmentCode      string `json:"DepartmentCode"`
		DepartmentCodeText  string `json:"DepartmentCodeText"`
		FunctionCode        string `json:"FunctionCode"`
		FunctionCodeText    string `json:"FunctionCodeText"`
		VIPReasonCode       string `json:"VIPReasonCode"`
		VIPReasonCodeText   string `json:"VIPReasonCodeText"`
		EntityLastChangedOn string `json:"EntityLastChangedOn"`
		ETag                string `json:"ETag"`
	} `json:"PartnerContactCollection"`
	APISchema   string   `json:"api_schema"`
	Accepter    []string `json:"accepter"`
	PartnerCode string   `json:"partner_code"`
	Deleted     bool     `json:"deleted"`
}

